### ISSUE TITLE
Errors with pytest

### ISSUE THREAD

**Issue by anardek** [UNC-CECL/brie#12]
@mcflugen - I'm getting errors in pytest regarding the "datadir" variable in test_bmi.py. Tried playing around with this, but I'm not really sure where these variables should be specified? In the toml? Or directly in this function?

**Comment by anardek** [comment]
I'm also getting errors in pytest for `test_ashton_vs_WaveAngleGenerator` here, but not on my machine. Not sure why.

**Comment by mcflugen** [comment]
@anardek the *datadir* error is probably because you haven't installed a testing requirement. The requirements for running the tests are listed in the *requirements-testing.txt* file. Try running,
```bash
$ pip install -r requirements-testing.txt
```
and then rerunning the tests.

Can you point me to the errors you are seeing for *test_ashton_vs_WaveAngleGenerator*.

**Comment by anardek** [comment]
Ah ha - I can't install the bmi-tester package. I updated pip to the most
recent version the other day. I wonder if that is the problem.

**Comment by anardek** [comment]
Also, here is a link to the brie errors: https://github.com/UNC-CECL/brie/runs/2877397533?check_suite_focus=true#step:7:765

Also, a screen shot
<img width="993" alt="Screen Shot 2021-06-22 at 1 10 51 PM" src="https://user-images.githubusercontent.com/57640439/122970127-82826380-d35b-11eb-9304-a493cd8eaf37.png">
